services:
  db:
    image: mysql:latest
    networks:
      - petclinic-network
    env_file:
      - ./.env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    ##image: petclinic:v1.0
    image: svitlanakizilpinar/petclinic:v1.0
    ## build: .
    networks:
      - petclinic-network
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

networks:
  petclinic-network:

volumes:
  db_data:
